### ISSUE TITLE
Update ferrocene-self-test

### ISSUE THREAD

**Issue by jonathanpallant** [ferrocene/ferrocene#107]
The ferrocene-self-test program needs to check the platform has a suitable system C compiler - one which can be made to use `ld.lld` as the linker.

It should try `cc`, then `gcc`, then `clang`, and report which one worked and what, if any, `-C linker=xxx` or `-C link-arg=xxx` options are required to use it.

**Comment by pietroalbini** [comment]
Yeah this is done, I'll open up a separate issue for a small followup task.
