### ISSUE TITLE
Verify that explicit linker arguments are propagated by the linker driver

### ISSUE THREAD

**Issue by pietroalbini** [ferrocene/ferrocene#146]
We should add a requirement in the safety manual and a check in the FST that:

1. Object files passed to the linker driver are forwarded to the linker.
2. Linker arguments passed via `-Wl,` (for example `-Wl,-foo`) are forwarded to the linker without the `-Wl,` prefix (like `-foo`).

The second point should cover the A53 errata flag if our target spec passes the flag via `-Wl,`. To check both things automatically in the FST, we can try passing random strings bare (for 1) and prefixed with `-Wl,` (for 2) and check whether they are passed to the fake linker.

**Comment by jonathanpallant** [comment]
https://github.com/ferrocene/ferrocene/pull/156 checks `-Wl,<foo>`

Object files are checked by virtue of the fact we can compile and execute a Rust program.

**Comment by jonathanpallant** [comment]
I think this is done?

**Comment by pietroalbini** [comment]
Yeah this is done.
