### ISSUE TITLE
Profile-Guided Optimization (PGO) and LLVM BOLT for the prebuilt binaries

### ISSUE THREAD

**Issue by zamazan4ik** [ferrocene/ferrocene#22]
Hi!

According to the https://github.com/ferrocene/ferrocene#installation link, there are prebuilt binaries. Are these binaries optimized with PGO and/or LLVM BOLT as it's already done for Rustc ([doc](https://rustc-dev-guide.rust-lang.org/building/optimized-build.html))?

For us it's important since we want to know - do we need to rebuild the compiler from scratch to improve compilation speed or we can use already-built PGO-optimized binaries.

**Comment by Hoverbear** [comment]
Hi! This is not a monitored support venue and is not suitable for sales or support inquiries.

Ferrocene is not built with PGO at this time. If that's important for your use of Ferrocene, please [contact us](https://ferrous-systems.com/contact/#ferrocene) and we can work with you on solutions.
