### ISSUE TITLE
fedora silverblue 38 build doc success

### ISSUE THREAD

**Issue by omac777** [ferrocene/ferrocene#33]
For anyone interested in using ferrocene on fedora silverblue 38

```
sudo rpm-ostree install 'gcc-c++' astyle autoconf automake binutils bison byacc cbmc ccache check cmake coan cproto cscope ctags ddrescue ElectricFence elfutils emacs ffmpeg-free flex gcc gdb glibc-devel gparted gstreamer1-svt-av1 indent insight langpacks-en lazarus libtool ltrace make nasm ninja-build openssl-devel perf pscan python-sphinx python3-scons remake scorep splint strace svt-av1 valgrind yasm zzuf
systemctl reboot
git clone https://github.com/ferrocene/ferrocene.git
cd ferrocene/
./configure 
python /var/home/cissy/ferrocene/x.py doc

```
Doing so built all the tools and the docs.

Afterwards you can navigate with your web browser to:
`file:///home/youruser/ferrocene/build/x86_64-unknown-linux-gnu/doc/index.html`

**Comment by omac777** [comment]
it would have been nice to see an option within the x.py doc to additionally build the pdf.

**Comment by Hoverbear** [comment]
Thank you for documenting how to build the docs on Fedora Silverblue! I'm going to be closing this issue as we do not make it a habit of documenting per-OS setup instructions for doc generation.

Please open a different issue if you'd like to propose a feature adding PDF documentation generation.
